; Smartwatch M5StickC Plus 2 — PlatformIO
; Hito 1: base (PowerManager + RTC + UiManager + Watchface)

[env:m5stick-c-plus2]
platform  = espressif32
board     = m5stick-c-plus2      ; board propio (boards/m5stick-c-plus2.json), variante m5stack_stickc_plus2
framework = arduino

monitor_speed = 115200
upload_speed  = 1500000

; El Plus 2 lleva 8 MB de flash
board_build.partitions = default_8MB.csv

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_CDC_ON_BOOT=0

lib_deps =
    m5stack/M5Unified@^0.2.0
    h2zero/NimBLE-Arduino@^2.1.0        ; BLE ligero para ANCS (llamadas) + CTS (hora)
    crankyoldgit/IRremoteESP8266@^2.8.6 ; emisor IR (TV-B-Gone)
